sonar.projectKey=vitaly-zdanevich_wikimedia_commons_pwa_viewer
sonar.organization=vitaly-zdanevich
sonar.sources=src,scripts
sonar.exclusions=**/*.test.ts,src/env.d.ts
sonar.tests=src,scripts
sonar.test.inclusions=**/*.test.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
